name: _flutterish_workspace
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - packages/flutterish
  - packages/flutterish_stepper
  - packages/flutterish_a2ui
  - packages/flutterish_a2ui_standard
  - packages/flutterish_image_cropper
  - packages/flutterish_pdf_viewer
  - example
